sudo: required

language: php

services:
  - docker

php:
  - 7.2

# addons:
#   sauce_connect: true

before_script:
  - docker ps -a
  - sleep 30

script:
  - ./test-unit.sh
  - ./test-integration.sh
