# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
      image: circleci/classic:201808-01
    working_directory: ~/minds # directory where steps will run
    steps:
      - checkout
      # run tests!
      - run: ./test-unit.sh
      - run: ./test-integration.sh
